### ISSUE TITLE
Fix mixed content being loaded

### ISSUE THREAD

**Issue by ethanhs** [ocf/ocfweb#463]
The hosting badges page of the docs seems to load mixed content, presumably due to `build_absolute_uri` [here](https://github.com/ocf/ocfweb/blob/30d0716b1ee90c8b1af2ea7889f3d662069a4e6a/ocfweb/docs/views/hosting_badges.py#L7) getting confused and thinking the site is being loaded as http.

**Comment by jvperrin** [comment]
My guess on this after doing a bit of investigation is that the extra nginx proxy layer added in #436 is setting the `X-Forwarded-Proto` header to `http` (requests to the ocfweb container are over http since they are behind death, which terminates SSL) when we've configured django to check that header to see if a request is made over http/https: https://github.com/ocf/ocfweb/blob/30d0716b1ee90c8b1af2ea7889f3d662069a4e6a/ocfweb/settings.py#L60

I think instead, we'd want to pass through the `X-Forwarded-Proto` header if possible since we trust the upstream proxy and the iptables firewalls should mostly prevent requests coming from other locations.

**Comment by jvperrin** [comment]
This doesn't appear to actually be resolved, as the [hosting badges page](https://www.ocf.berkeley.edu/docs/services/vhost/badges/) still has mixed content after #472 was deployed.

**Comment by jvperrin** [comment]
Nice, that fixed it
