### ISSUE TITLE
Move the lab usage leaderboard somewhere else

### ISSUE THREAD

**Issue by dkess** [ocf/ocfweb#477]
The stats page serves a bit of a dual purpose right now, where some of it is for things we want to show off (general lab usage, printer usage), and others are for staff benefit/fun (this includes the leaderboard, but also the list of staff currently in the lab).

We should try to separate these out somehow. I'm not really sure which page would be best for it to go on, or where we would even put a new page, so suggestions here would be welcome.

**Comment by cg505** [comment]
we should delete the leaderboard and move staff in lab to the staff hours page

**Comment by kpengboy** [comment]
I would keep the leaderboard somewhere, it's entertaining

**Comment by abizer** [comment]
ning has written the code for this

**Comment by ethanhs** [comment]
I think this is complete with https://github.com/ocf/ocfweb/pull/490 so closing. The leaderboard was moved to a session tracking page. I like the list of staff in the lab on the first page because I can check ocf.io/stats if I don't want to ping create.

If you disagree and want to move it off the first page, feel free to re-open this issue.

**Comment by dkess** [comment]
If we want to have one tab for "staff use" and another one for "general lab statistics that the public might care about", there's definitely room to reorganize stuff more, but that can be in a separate issue.
